# Generated by Django 2.2.7 on 2019-12-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hcasdata',
            old_name='runhorus',
            new_name='runhours',
        ),
    ]
