# Generated by Django 2.2.7 on 2019-12-15 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0002_auto_20191215_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chpdata',
            options={'verbose_name': '6 - CHPdata', 'verbose_name_plural': '6 - CHPdata'},
        ),
        migrations.AlterModelOptions(
            name='controlchp',
            options={'verbose_name': '9 - controlchp', 'verbose_name_plural': '9 - controlchp'},
        ),
        migrations.AlterModelOptions(
            name='controlhvas',
            options={'verbose_name': '10 - controlhvas', 'verbose_name_plural': '10 - controlhvas'},
        ),
        migrations.AlterModelOptions(
            name='devices',
            options={'verbose_name': '2 - Devices', 'verbose_name_plural': '2 - Devices'},
        ),
        migrations.AlterModelOptions(
            name='devicestype',
            options={'verbose_name': '3 - Devicetype', 'verbose_name_plural': '3 - Devicetype'},
        ),
        migrations.AlterModelOptions(
            name='egcdata',
            options={'verbose_name': '7 - Emergency genset data', 'verbose_name_plural': '7 - Emergency genset data'},
        ),
        migrations.AlterModelOptions(
            name='hcasdata',
            options={'verbose_name': '5 - Hcasdata', 'verbose_name_plural': '5 - Hcasdata'},
        ),
        migrations.AlterModelOptions(
            name='mvpdata',
            options={'verbose_name': '8 - mvpdata', 'verbose_name_plural': '8 - mvpdata'},
        ),
        migrations.AlterModelOptions(
            name='subcustomer',
            options={'verbose_name': '1 - Customer', 'verbose_name_plural': '1 - Customers'},
        ),
    ]
