# Generated by Django 2.2.7 on 2019-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0003_auto_20191215_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpdata',
            name='exhaustgastemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='exhaustgas temp'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='motorintemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='motor in temp'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='motorouttemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='motor out temp'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='oilpressure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Oil pressure'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='oiltemp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='oil temp'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='wastgastemppri',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='wastgas pri temp'),
        ),
        migrations.AlterField(
            model_name='chpdata',
            name='wastgastempsec',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='wastgas sec temp'),
        ),
    ]
