# Generated by Django 2.2.7 on 2019-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0004_auto_20191215_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egcdata',
            name='operstate',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Operation state'),
        ),
    ]
