# Generated by Django 2.2.7 on 2019-12-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0005_auto_20191215_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlhvas',
            name='devicemodecmd',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='device Mode'),
        ),
        migrations.AddField(
            model_name='controlhvas',
            name='operationmodecmd',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='operation Mode'),
        ),
        migrations.AlterField(
            model_name='controlchp',
            name='resetcmd',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='reset cmd'),
        ),
        migrations.AlterField(
            model_name='controlchp',
            name='tempreq',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='requested temperatur request'),
        ),
        migrations.AlterField(
            model_name='controlhvas',
            name='resetcmd',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='reset command'),
        ),
    ]
