# Generated by Django 2.2.7 on 2019-12-15 18:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0006_auto_20191215_1913'),
    ]

    operations = [
        migrations.CreateModel(
            name='controlmvp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(default=' ', max_length=25, verbose_name='IP-address')),
                ('resetcmd', models.PositiveSmallIntegerField(default=0, verbose_name='reset command')),
                ('CB1cmd', models.PositiveSmallIntegerField(default=0, verbose_name='CB1 Open/close')),
                ('CB2cmd', models.PositiveSmallIntegerField(default=0, verbose_name='CB2 Open/close')),
                ('CB3cmd', models.PositiveSmallIntegerField(default=0, verbose_name='CB3 Open/close')),
                ('CB4cmd', models.PositiveSmallIntegerField(default=0, verbose_name='CB4 Open/close')),
                ('requestinfo', models.TextField(verbose_name='Info')),
                ('inserttime', models.DateTimeField(verbose_name='Inserttime')),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.devices')),
            ],
            options={
                'verbose_name': '12 - controlmvp',
                'verbose_name_plural': '12 - controlmvp',
            },
        ),
        migrations.CreateModel(
            name='controlegc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ipaddr', models.CharField(default=' ', max_length=25, verbose_name='IP-address')),
                ('resetcmd', models.PositiveSmallIntegerField(default=0, verbose_name='reset command')),
                ('operationmodecmd', models.PositiveSmallIntegerField(default=0, verbose_name='operation Mode')),
                ('devicemodecmd', models.PositiveSmallIntegerField(default=0, verbose_name='device Mode')),
                ('requestinfo', models.TextField(verbose_name='Info')),
                ('inserttime', models.DateTimeField(verbose_name='Inserttime')),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.devices')),
            ],
            options={
                'verbose_name': '11 - controlegc',
                'verbose_name_plural': '11 - controlegc',
            },
        ),
    ]
