# Generated by Django 2.2.7 on 2019-12-15 18:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0007_controlegc_controlmvp'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemalarms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boarderstate', models.PositiveSmallIntegerField(default=0, help_text='Please choose border value higer or lower', verbose_name='requested boarder')),
                ('boardervalue', models.IntegerField(default=0, help_text='Please insert boarder value', verbose_name='Boarder Value')),
                ('boarderinfo', models.TextField(verbose_name='Info')),
                ('inserttime', models.DateTimeField(verbose_name='Inserttime')),
                ('deviceid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supervision.devices')),
            ],
            options={
                'verbose_name': '13 - systemalarms',
                'verbose_name_plural': '13 - systemalarms',
            },
        ),
    ]
