# Generated by Django 2.2.7 on 2019-12-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0008_systemalarms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemalarms',
            name='boarderstate',
            field=models.PositiveSmallIntegerField(choices=[(1, 'test1'), (2, 'test2')], default=1, help_text='Please choose border value higer or lower', verbose_name='requested boarder'),
        ),
    ]
