# Generated by Django 2.2.7 on 2019-12-15 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervision', '0009_auto_20191215_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemalarms',
            old_name='boarderstate',
            new_name='boardercondition',
        ),
        migrations.AddField(
            model_name='systemalarms',
            name='measurevalue',
            field=models.CharField(default=' ', max_length=25, verbose_name='Requested temp or state'),
        ),
    ]
